"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
command_timeout = 150
continuation_prompt = "[▸▹ ](dimmed white)"

format = """($nix_shell$fill$git_metrics\n)$cmd_duration\
$hostname\
$localip\
$jobs\
$sudo\
$status\
$character\
$username\
$directory"""

right_format = """$git_branch\
$git_state\
$git_status\
$time"""

[fill]
symbol = ' '

[character]
format = "$symbol "
success_symbol = "[▲](white)"
error_symbol = "[△](red)"
vimcmd_symbol = "[■](dimmed green)"
# not supported in zsh
vimcmd_replace_one_symbol = "◌"
vimcmd_replace_symbol = "□"
vimcmd_visual_symbol = "▼"

[sudo]
format = "[$symbol]($style)"
style = "bold italic bright-purple"
symbol = "⋈┈"
disabled = false

[username]
style_user = "bright-yellow bold italic"
style_root = "purple bold italic"
format = "[⭘ $user]($style) "
disabled = false
show_always = false

[directory]
truncate_to_repo = false
truncation_symbol = '…/'
read_only = " ◈"
use_os_path_sep = true
style = "italic blue"
format = '[$path]($style)[$read_only]($read_only_style) '
repo_root_style = 'bold blue'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) '

[cmd_duration]
format = "[◄ $duration ](italic white)"
show_notifications = true

[jobs]
format = "[$symbol$number]($style) "
style = "white"
symbol = "[▶](blue italic)"

[localip]
ssh_only = true
format = " ◯[$localipv4](bold magenta)"
disabled = false

[status]
disabled = false
format = "[$symbol$status]($style) "
symbol = "✗"
style = "bold red"

[time]
disabled = false
format = "[ $time]($style)"
time_format = "%R"
utc_time_offset = "local"
style = "italic dimmed white"

[git_branch]
format = " [$symbol$branch(:$remote_branch)]($style)"
symbol = " "
style = "bright-blue"
truncation_symbol = "⋯"
truncation_length = 11
only_attached = true

[git_metrics]
format = '([▴$added]($added_style))([▿$deleted]($deleted_style))'
added_style = 'italic dimmed green'
deleted_style = 'italic dimmed red'
ignore_submodules = true
disabled = false

[git_status]
ignore_submodules = false
style = "dimmed white"
format = "[\\[$ahead_behind$staged$modified$untracked$renamed$deleted$conflicted$stashed\\]]($style)"
conflicted = "[!](italic bright-magenta)"
ahead = "[⇡](italic green)"
behind = "[⇣](italic red)"
diverged = "[⇡⇣](italic bright-magenta)"
untracked = "[?](italic bright-yellow)"
stashed = "[≡](italic white)"
modified = "[~](italic yellow)"
staged = "[+](italic bright-cyan)"
renamed = "[→](italic bright-blue)"
deleted = "[-](italic red)"

[nix_shell]
style = 'bold italic dimmed blue'
symbol = " "
format = '[$symbol nix $state]($style) [$name](italic dimmed white)'
impure_msg = '[⌽](bold dimmed red)'
pure_msg = '[⌾](bold dimmed green)'
unknown_msg = '[◌](bold dimmed yellow)'
